import type { TutorSession, TutorTask } from "./types";

/** Small authored vocabulary. Unknown concepts remain episode-local, never guessed from labels. */
export const TUTOR_CONCEPTS = {
  "present-perfect-duration": { label: "Falar sobre duração com present perfect", rubric: "Express an action or state that started in the past and continues now, with a valid present perfect form and duration/start point. Accept simple or continuous forms when natural. A past-only event or avoidance of duration does not demonstrate this skill." },
  "polite-requests": { label: "Fazer pedidos com educação", rubric: "Make a clear, appropriately polite request using a valid request construction. Accept natural alternatives; do not require a particular modal." },
  "work-status": {"label": "Dar um status de trabalho", "rubric": "Give a concrete work update distinguishing completed work, current work and what remains. Accept natural simple or compound sentences and valid tense alternatives. A vague statement without progress or remaining work does not demonstrate the skill."},
  "problem-cause": {"label": "Explicar um problema e sua causa", "rubric": "Explain a concrete problem and a plausible cause with a clear causal relationship. Accept because, due to, so, or natural alternatives when the relationship is clear. Listing unrelated facts or giving only the problem does not demonstrate the skill."},
  "polite-disagreement": {"label": "Discordar com educação", "rubric": "Express a different opinion respectfully and give a relevant reason or alternative. Accept direct but considerate disagreement and natural hedging; no specific formula is required. Agreement, insults, or a bare unrelated opinion do not demonstrate disagreement."},
  "clarification": {"label": "Pedir esclarecimento", "rubric": "Ask a specific question to resolve an ambiguity or missing information. Accept natural direct questions, polite requests for explanation or confirmation. Repeating a vague statement, guessing, or saying only that it is unclear does not demonstrate the skill."},
  "next-steps": {"label": "Propor e confirmar próximos passos", "rubric": "Propose a concrete future action with an owner and timing, and seek confirmation or agreement. Accept natural suggestions and plans; no specific modal is required. A vague intention, past-only report or action without confirmation does not demonstrate the whole skill."},
  "past-experience": {"label": "Descrever uma experiência passada", "rubric": "Describe a completed past event with a clear past time or finished context, using appropriate past forms. Accept natural past simple forms, including irregular verbs, and other forms where justified. A current routine or avoidance of the past event does not demonstrate the skill."},
} as const;
export type TutorConceptId = keyof typeof TUTOR_CONCEPTS;
export function isTutorConceptId(value: unknown): value is TutorConceptId {
  return typeof value === "string" && Object.hasOwn(TUTOR_CONCEPTS, value);
}

export const tutorScenarios: { conceptId: TutorConceptId; contextId: string; task: TutorTask }[] = [
  { conceptId: "present-perfect-duration", contextId: "professional-experience", task: { scenarioId: "duration-interview-v1", goal: "Contar sua experiência profissional", situation: "Você está em uma entrevista. Conte sobre uma tecnologia que usa no trabalho e há quanto tempo a utiliza.", instruction: "Tell me about your professional experience. Include how long you have used a technology you still work with.", successCriteria: "Descrever uma experiência que continua no presente e sua duração ou data de início." } },
  { conceptId: "present-perfect-duration", contextId: "remote-work", task: { scenarioId: "duration-remote-v1", goal: "Conversar sobre trabalho remoto", situation: "Um colega novo quer conhecer sua rotina. Conte há quanto tempo trabalha remotamente e um aspecto dessa experiência.", instruction: "Tell your new colleague about working remotely. Include when you started or how long you have done it.", successCriteria: "Comunicar a duração de uma experiência de trabalho remoto que continua no presente." } },
  { conceptId: "present-perfect-duration", contextId: "learning-technology", task: { scenarioId: "duration-learning-v1", goal: "Contar o que está estudando", situation: "Você participa de um encontro de tecnologia. Conte sobre algo que começou a estudar e continua estudando, incluindo há quanto tempo.", instruction: "Tell someone about a technology you are learning. Include when you started or how long you have studied it.", successCriteria: "Comunicar a duração de um estudo iniciado no passado e ainda em andamento." } },
  { conceptId: "present-perfect-duration", contextId: "living-in-city", task: { scenarioId: "duration-city-v1", goal: "Apresentar sua vida na cidade", situation: "Um visitante pergunta sobre a cidade onde você mora. Conte há quanto tempo vive nela e algo de que gosta.", instruction: "Tell a visitor about living in your city. Include when you moved there or how long it has been your home.", successCriteria: "Expressar há quanto tempo mora na cidade e compartilhar uma informação relevante." } },
  { conceptId: "polite-requests", contextId: "reschedule-meeting", task: { scenarioId: "request-meeting-v1", goal: "Remarcar uma reunião", situation: "Você não pode participar da reunião de terça-feira. Peça a um colega para mudar para sexta-feira.", instruction: "Ask your colleague to move Tuesday's meeting to Friday.", successCriteria: "Pedir a mudança de forma clara e educada, indicando a nova data." } },
  { conceptId: "polite-requests", contextId: "code-review", task: { scenarioId: "request-review-v1", goal: "Pedir uma revisão de código", situation: "Você terminou uma mudança e precisa de uma revisão antes do fim do dia. Faça o pedido a alguém da equipe.", instruction: "Ask a teammate to review your code before the end of the day.", successCriteria: "Pedir a revisão com educação e informar o prazo." } },
  { conceptId: "polite-requests", contextId: "recruiter-details", task: { scenarioId: "request-recruiter-v1", goal: "Pedir informações a um recrutador", situation: "Um recrutador enviou uma vaga sem detalhes sobre o horário. Peça essa informação.", instruction: "Ask the recruiter for information about the working hours.", successCriteria: "Fazer um pedido educado e específico sobre o horário." } },
  {"conceptId": "work-status", "contextId": "daily-meeting", "task": {"scenarioId": "status-meeting-v1", "goal": "Give a work update", "situation": "You finished the login screen. You are testing it today. The password reset still needs work. Update your team at the morning meeting.", "instruction": "Update the team on completed work, current work and what remains.", "successCriteria": "Report what is done, what is happening now and what is still needed."}},
  {"conceptId": "work-status", "contextId": "client-delivery", "task": {"scenarioId": "status-client-v1", "goal": "Give a work update", "situation": "The client report is drafted. You are checking the figures. The charts will be added tomorrow. Send the client a short update.", "instruction": "Tell the client the progress of the report.", "successCriteria": "Distinguish the finished draft, the current checks and the remaining charts."}},
  {"conceptId": "work-status", "contextId": "event-preparation", "task": {"scenarioId": "status-event-v1", "goal": "Give a work update", "situation": "The room is booked. You are inviting speakers. You still need to arrange lunch. Update the event organizer.", "instruction": "Tell the organizer where preparations stand.", "successCriteria": "Communicate completed, ongoing and remaining preparations."}},
  {"conceptId": "problem-cause", "contextId": "service-outage", "task": {"scenarioId": "cause-service-v1", "goal": "Explain a problem and its cause", "situation": "Customers cannot sign in. The authentication server is offline. Explain the problem to support.", "instruction": "Explain what is failing and why.", "successCriteria": "Connect the sign-in failure to the unavailable server."}},
  {"conceptId": "problem-cause", "contextId": "late-delivery", "task": {"scenarioId": "cause-delivery-v1", "goal": "Explain a problem and its cause", "situation": "A shipment will arrive late. Heavy rain closed the main road. Explain the delay to a customer.", "instruction": "Explain the delay and its cause.", "successCriteria": "Connect the late shipment to the road closure."}},
  {"conceptId": "problem-cause", "contextId": "budget-change", "task": {"scenarioId": "cause-budget-v1", "goal": "Explain a problem and its cause", "situation": "The project costs more than planned. The supplier raised material prices. Explain this to your manager.", "instruction": "Explain the budget problem and the reason.", "successCriteria": "Connect the higher cost to the increased material prices."}},
  {"conceptId": "polite-disagreement", "contextId": "release-decision", "task": {"scenarioId": "disagree-release-v1", "goal": "Disagree respectfully", "situation": "A colleague wants to release the app today. Tests are unfinished and you prefer to wait until tomorrow. Reply to the colleague.", "instruction": "Explain your different view respectfully and give a reason.", "successCriteria": "Disagree with releasing today and explain the testing concern."}},
  {"conceptId": "polite-disagreement", "contextId": "office-policy", "task": {"scenarioId": "disagree-office-v1", "goal": "Disagree respectfully", "situation": "Your manager suggests every meeting must be in person. Some teammates live far away. You think online meetings should remain an option.", "instruction": "Respond respectfully with your view and a reason.", "successCriteria": "Question the in-person-only proposal and explain the travel issue."}},
  {"conceptId": "polite-disagreement", "contextId": "training-choice", "task": {"scenarioId": "disagree-training-v1", "goal": "Disagree respectfully", "situation": "A teammate wants a long lecture for new staff. You think a short workshop with practice would help more. Explain your view.", "instruction": "Offer a different training approach politely and explain why.", "successCriteria": "Disagree with a lecture-only approach and give a reason for practical training."}},
  {"conceptId": "clarification", "contextId": "deadline-ambiguity", "task": {"scenarioId": "clarify-deadline-v1", "goal": "Ask for clarification", "situation": "A client asks for the file by the end of the week, but your team works across time zones. You need the exact day and time.", "instruction": "Ask the client to clarify the deadline.", "successCriteria": "Ask for the exact day, time and relevant time zone."}},
  {"conceptId": "clarification", "contextId": "ambiguous-feedback", "task": {"scenarioId": "clarify-feedback-v1", "goal": "Ask for clarification", "situation": "A reviewer says your report should be more detailed but does not say which section. You need a specific example.", "instruction": "Ask the reviewer what to expand.", "successCriteria": "Ask which section needs detail and request an example."}},
  {"conceptId": "clarification", "contextId": "task-ownership", "task": {"scenarioId": "clarify-owner-v1", "goal": "Ask for clarification", "situation": "In a meeting, someone says we should contact the supplier. Nobody is assigned. You need to know who will do it.", "instruction": "Ask a question to clarify responsibility.", "successCriteria": "Ask who is responsible for contacting the supplier."}},
  {"conceptId": "next-steps", "contextId": "bug-followup", "task": {"scenarioId": "steps-bug-v1", "goal": "Agree on next steps", "situation": "You found a bug with a teammate. You can investigate today and the teammate can test tomorrow. Propose this plan and check agreement.", "instruction": "Propose who does what and when, then ask for agreement.", "successCriteria": "State both actions and their timing, and seek confirmation."}},
  {"conceptId": "next-steps", "contextId": "proposal-review", "task": {"scenarioId": "steps-proposal-v1", "goal": "Agree on next steps", "situation": "A client needs a proposal. You can send a draft on Monday and ask the client to review it on Tuesday. Agree on the plan.", "instruction": "Propose the delivery and review plan and confirm it.", "successCriteria": "Specify owners and days for the draft and review, and check agreement."}},
  {"conceptId": "next-steps", "contextId": "workshop-plan", "task": {"scenarioId": "steps-workshop-v1", "goal": "Agree on next steps", "situation": "You and a colleague are planning a workshop. You can book the room today; the colleague can invite people tomorrow. Propose the next steps.", "instruction": "Suggest the two actions with timing and ask whether the plan works.", "successCriteria": "Assign the booking and invitations with timing and seek agreement."}},
  {"conceptId": "past-experience", "contextId": "past-project", "task": {"scenarioId": "past-project-v1", "goal": "Describe a past experience", "situation": "In an interview, describe a project you finished last year and what you did on it.", "instruction": "Describe a completed project and your contribution.", "successCriteria": "Describe your actions in a finished project with a past time reference."}},
  {"conceptId": "past-experience", "contextId": "past-incident", "task": {"scenarioId": "past-incident-v1", "goal": "Describe a past experience", "situation": "Your team asks about a problem you solved last week. Describe what happened and what you did.", "instruction": "Tell the team about the incident and your actions.", "successCriteria": "Describe a finished incident and the actions you took last week."}},
  {"conceptId": "past-experience", "contextId": "past-training", "task": {"scenarioId": "past-training-v1", "goal": "Describe a past experience", "situation": "You attended a course last month. Tell a colleague what you learned and one activity you did.", "instruction": "Describe the completed course and an activity.", "successCriteria": "Describe learning and participation in a course that ended last month."}},
];

export function verifiedTutorContext(task: TutorTask, conceptId?: string): string | undefined {
  const scenario = tutorScenarios.find(s => s.conceptId === conceptId && s.task.scenarioId === task.scenarioId);
  // An ID supplied by a model or a restored backup alone is not verification.
  return scenario && (["goal", "situation", "instruction", "successCriteria"] as const).every(k => scenario.task[k] === task[k]) ? scenario.contextId : undefined;
}

export function chooseTutorScenario(conceptId: string, sessions: TutorSession[]): TutorTask | undefined {
  const options = tutorScenarios.filter(s => s.conceptId === conceptId);
  const lastUse = (id: string) => Math.max(0, ...sessions.filter(s => s.task.scenarioId === id).map(s => s.createdAt));
  const next = [...options].sort((a, b) => lastUse(a.task.scenarioId!) - lastUse(b.task.scenarioId!))[0];
  return next ? { ...next.task } : undefined;
}

export const tutorScenarioFor = (id: string): TutorTask => {
  const task = tutorScenarios.find(s => s.task.scenarioId === id)?.task;
  if (!task) throw new Error("Situação desconhecida.");
  return { ...task };
};

export function tutorConceptForTask(task: TutorTask): TutorConceptId | undefined {
  return tutorScenarios.find(s => verifiedTutorContext(task, s.conceptId))?.conceptId;
}
